### ISSUE TITLE
"There appears to be a problem with your internet connection"

### ISSUE THREAD

**Issue by abbycabs** [mozilla/mattermoz#69]
Seeing this now:

![screen shot 2016-03-17 at 16 23 55](https://cloud.githubusercontent.com/assets/617994/13860099/0dc0dbc0-ec5d-11e5-8cfa-91c819fbbdfd.png)

Still able to message people though, and the rest of my internet is fine.

**Comment by gideonthomas** [comment]
Ok so this happens under a couple of different conditions, all related to **poor** or no internet connection. This can also happen when you switch from one WiFi connection to another. 
XHRs won't go through and it's the same case with websocket data as well. 
I feel like this message is the right way to deal with it especially since so far there have been no communication issues or missed chats. We should probably close for now and open again if this really becomes a problem.
