### ISSUE TITLE
Figure out default channels

### ISSUE THREAD

**Issue by simonwex** [mozilla/mattermoz#7]
There are many ways to organize our channels.
#### There are two (potentially conflicting) goals:
- Ensure people across the organization see this as a place for their conversations, not just engineering chatter (This shouldn't feel like IRC) 
- Make sure that engineering, design, etc have a place to have their conversations
### Division of conversations

At least in the case of engineering, the organization of the current IRC channels seems to be vestigial. To better facilitate communication, there are a few ways to consider creating channels
#### Software project
- Webmaker
- Teach
- Donate
- Science
#### Role
- PM
- Engineering
- Design
- etc
#### Business Unit
- Advocacy
- MLN
  - Open Science

**Comment by alanmoo** [comment]
There's also the 

#### "Let it grow" approach

There are 2 channels created by default with a Mattermost instance- `Off Topic` and `Town Square`. You can't leave `Town Square`, so that would be the de-facto All MoFo channel. From there we may want to create channels as conversations in other channels become crowded. This will probably result in a combination of all 3 of the above approaches. For example, I'd bet engineering chatter plays a pretty significant roll in `Town Square` that we don't want to bother the rest of the org with, so we could start off with a channel for it. If certain projects become conversational focuses, or if someone wants to have a conversation about something specific but there isn't a place for it, they could simply create a channel. Channels could even be useful for smaller temporary groups, like organizing a small work-week.

**Comment by alanmoo** [comment]
@simonwex do you want to go with my approach? Anyone can create channels, so I think this problem will solve itself organically. Let's close this?

**Comment by simonwex** [comment]
@alanmoo yeah, let's. We might need to revisit this after a couple weeks of engineering + design playing around.

**Comment by alanmoo** [comment]
👍
